### ISSUE TITLE
WizardLM-Uncensored-13B - 500 internal error

### ISSUE THREAD

**Issue by edricus** [serge-chat/serge#421]
### Bug description

When trying to download WizardLM-Uncensored-13B, it fails with error 500  
I can download other models just fine (tested with GPT4All)

### Steps to reproduce

Deploy Serge

 - Try to download WizardLM-Uncensored-13B
 - Observe logs

### Environment Information

Docker version : 20.10.24
Docker-compose version : 1.29.2
Image used : ghcr.io/serge-chat/serge:latest
OS : Debian 12

### Relevant log output

```shell
serge    | INFO:     172.18.0.2:35396 - "GET /model/all HTTP/1.1" 200 OK
serge    | Downloading WizardLM-Uncensored-13B model from TheBloke/WizardLM-13B-Uncensored-GGML...
serge    | INFO:     172.18.0.2:35390 - "POST /model/WizardLM-Uncensored-13B/download HTTP/1.1" 500 Internal Server Error
serge    | ERROR:    Exception in ASGI application
serge    | Traceback (most recent call last):
serge    |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
serge    |     result = await app(  # type: ignore[func-returns-value]
serge    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
serge    |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
serge    |     return await self.app(scope, receive, send)
serge    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
serge    |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
serge    |     await super().__call__(scope, receive, send)
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
serge    |     await self.middleware_stack(scope, receive, send)
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
serge    |     raise exc
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
serge    |     await self.app(scope, receive, _send)
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 92, in __call__
serge    |     await self.simple_response(scope, receive, send, request_headers=headers)
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 147, in simple_response
serge    |     await self.app(scope, receive, send)
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 109, in __call__
serge    |     await response(scope, receive, send)
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 270, in __call__
serge    |     async with anyio.create_task_group() as task_group:
serge    |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
serge    |     raise exceptions[0]
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 273, in wrap
serge    |     await func()
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 134, in stream_response
serge    |     return await super().stream_response(send)
serge    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 262, in stream_response
serge    |     async for chunk in self.body_iterator:
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 98, in body_stream
serge    |     raise app_exc
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
serge    |     await self.app(scope, receive_or_disconnect, send_no_error)
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
serge    |     raise exc
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
serge    |     await self.app(scope, receive, sender)
serge    |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
serge    |     raise e
serge    |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
serge    |     await self.app(scope, receive, send)
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
serge    |     await route.handle(scope, receive, send)
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 443, in handle
serge    |     await self.app(scope, receive, send)
serge    |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
serge    |     await super().__call__(scope, receive, send)
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
serge    |     await self.middleware_stack(scope, receive, send)
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
serge    |     raise exc
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
serge    |     await self.app(scope, receive, _send)
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
serge    |     raise exc
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
serge    |     await self.app(scope, receive, sender)
serge    |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
serge    |     raise e
serge    |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
serge    |     await self.app(scope, receive, send)
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
serge    |     await route.handle(scope, receive, send)
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
serge    |     await self.app(scope, receive, send)
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
serge    |     response = await func(request)
serge    |                ^^^^^^^^^^^^^^^^^^^
serge    |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
serge    |     raw_response = await run_endpoint_function(
serge    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
serge    |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
serge    |     return await run_in_threadpool(dependant.call, **values)
serge    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
serge    |   File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
serge    |     return await anyio.to_thread.run_sync(func, *args)
serge    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
serge    |   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
serge    |     return await get_asynclib().run_sync_in_worker_thread(
serge    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
serge    |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
serge    |     return await future
serge    |            ^^^^^^^^^^^^
serge    |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
serge    |     result = context.run(func, *args)
serge    |              ^^^^^^^^^^^^^^^^^^^^^^^^
serge    |   File "/usr/local/lib/python3.11/site-packages/serge/routers/model.py", line 344, in download_model
serge    |     urllib.request.urlretrieve(url, WEIGHTS + f"{model_name}.bin.tmp")
serge    |   File "/usr/local/lib/python3.11/urllib/request.py", line 241, in urlretrieve
serge    |     with contextlib.closing(urlopen(url, data)) as fp:
serge    |                             ^^^^^^^^^^^^^^^^^^
serge    |   File "/usr/local/lib/python3.11/urllib/request.py", line 216, in urlopen
serge    |     return opener.open(url, data, timeout)
serge    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
serge    |   File "/usr/local/lib/python3.11/urllib/request.py", line 525, in open
serge    |     response = meth(req, response)
serge    |                ^^^^^^^^^^^^^^^^^^^
serge    |   File "/usr/local/lib/python3.11/urllib/request.py", line 634, in http_response
serge    |     response = self.parent.error(
serge    |                ^^^^^^^^^^^^^^^^^^
serge    |   File "/usr/local/lib/python3.11/urllib/request.py", line 563, in error
serge    |     return self._call_chain(*args)
serge    |            ^^^^^^^^^^^^^^^^^^^^^^^
serge    |   File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
serge    |     result = func(*args)
serge    |              ^^^^^^^^^^^
serge    |   File "/usr/local/lib/python3.11/urllib/request.py", line 643, in http_error_default
serge    |     raise HTTPError(req.full_url, code, msg, hdrs, fp)
serge    | urllib.error.HTTPError: HTTP Error 404: Not Found
```
```


### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by pabl-o-ce** [comment]
I check it is a typo error of my part
