### ISSUE TITLE
Issues loading Facebook-LLaMA2-70B

### ISSUE THREAD

**Issue by overlordian** [serge-chat/serge#675]
### Bug description

When trying to start a new chat with "Facebook-LLaMA2-70B" the never changes to the chat page and no load is shown on the CPU (tends to be a small spike starting any chat).  Looking through the logs I found that Serge has an:  "error loading model: llama.cpp: tensor 'layers.0.attention.wk.weight' has wrong shape; expected  8192 x  8192, got  8192 x  1024
llama_load_model_from_file: failed to load model"
I have deleted and download a couple of times now with no luck
I have also deleted the docker container and deleted the volumes.  I recreated both volumes and started a new container.  Downloaded 70B again and the results were the same error.

### Steps to reproduce

download Facebook-LLaMA2-70B and try to start a new chat

### Environment Information

Docker version 24.0.4, build 3713ee1  [portainer 2.18.4]
Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-79-generic x86_64)
Intel Xeon CPU E5-2690 v4
Chrome 115.0.5790.102

### Relevant log output

```shell
llama.cpp: loading model from /usr/src/app/weights/Facebook-LLaMA2-70B.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 8192
llama_model_load_internal: n_mult     = 4096
llama_model_load_internal: n_head     = 64
llama_model_load_internal: n_layer    = 80
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 24576
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 65B
llama_model_load_internal: ggml ctx size =    0.18 MB
error loading model: llama.cpp: tensor 'layers.0.attention.wk.weight' has wrong shape; expected  8192 x  8192, got  8192 x  1024
llama_load_model_from_file: failed to load model
INFO:     xxx.xxx.xxx.xxx:60656 - "POST /chat/?temperature=0.1&top_k=50&max_length=256&top_p=0.95&context_window=512&repeat_last_n=64&model=Facebook-LLaMA2-70B&n_threads=4&repeat_penalty=1.3&init_prompt=Below+is+an+instruction+that+describes+a+task.+Write+a+response+that+appropriately+completes+the+request. HTTP/1.1" 500 Internal Server Error
Exception ignored in: <function Llama.__del__ at 0x7f434520e020>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/llama_cpp/llama.py", line 1440, in __del__
    if self.ctx is not None:
       ^^^^^^^^
AttributeError: 'Llama' object has no attribute 'ctx'
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 109, in __call__
    await response(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 134, in stream_response
    return await super().stream_response(send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 98, in body_stream
    raise app_exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/serge/routers/chat.py", line 37, in create_new_chat
    raise ValueError(f"Model can't be found: {exc}")
ValueError: Model can't be found:
```

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by bottiger** [comment]
Same problem here. Seems to be a general problem

**Comment by gaby** [comment]
There's another error happening here too: 

```
It can't find Facebook-LLaMA2-70B.bin
```

**Comment by gaby** [comment]
According to the models.json the file should be `llama-2-70b-chat.ggmlv3.q4_0.bin`

Source: https://github.com/serge-chat/serge/blob/main/api/src/serge/data/models.json#L366C38-L366C70

@overlordian I'm confused why are you sending `Facebook-LLaMA2-70B.bin` instead?

**Comment by gaby** [comment]
@overlordian This is a llama-cpp-python issue already reported there

**Comment by overlordian** [comment]
I see very good.  I didn't realize that it stemmed from llmaa-cpp.  Glad someone is on it.  Thank you.

**Comment by CorentinWicht** [comment]
> I see very good. I didn't realize that it stemmed from llmaa-cpp. Glad someone is on it. Thank you.

From what I read the issue is liked to llama-cpp-python but not llama-cpp:
[https://huggingface.co/TheBloke/Llama-2-70B-Chat-GGML/discussions/6](https://huggingface.co/TheBloke/Llama-2-70B-Chat-GGML/discussions/6)
They seem to be working on this issue:
https://github.com/abetlen/llama-cpp-python/pull/522[https://github.com/abetlen/llama-cpp-python/pull/522](url).

Nevertheless, to quote TheBloke:
![image](https://github.com/serge-chat/serge/assets/52161904/093f1b03-262e-4521-9ec7-7e14e5cf27df)

How will these GGUF models be integrated into upcoming Serge releases?

**Comment by gaby** [comment]
Closing this, the issue is fixed with the new models that we plan on adding to Serge this month. The llama-cpo-python team removed the gqa field
