### ISSUE TITLE
🐛 [Bug]: Seems like support for CPU-only is gone with the new version of serge?

### ISSUE THREAD

**Issue by gitwildnow** [serge-chat/serge#737]
### Bug description

I've used serge for several months. Last night Watchtower got a new version of serge. Now I can't do a chat. I tried a total reinstall of everything and using a 7b model on a 16GB server.

My log ends with this:
n_gpu_layers
      |   none is not an allowed value (type=type_error.none.not_allowed)

Does that indicate GPUs are needed now? That blows me out of the water if so.

### Steps to reproduce

Start Serge. Download a model such as Kualo-7B. Accept default model settings are press [Start a New Chat]. No response in the browser. Container log ends with:
n_gpu_layers
      |   none is not an allowed value (type=type_error.none.not_allowed)

### Environment Information

Docker version 24.0.6, build ed223bc
OS: Ubunto Linux 20.04
CPU: Intel Xeon D-1527 (serge runs in a linux VM)

### Relevant log output

```shell
|   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
  |     raise exc
  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 92, in __call__
  |     await self.simple_response(scope, receive, send, request_headers=headers)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 147, in simple_response
  |     await self.app(scope, receive, send)
  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 106, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 664, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 277, in __call__
    |     await wrap(partial(self.listen_for_disconnect, receive))
    |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 273, in wrap
    |     await func()
    |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 250, in listen_for_disconnect
    |     message = await receive()
    |               ^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 587, in receive
    |     await self.message_event.wait()
    |   File "/usr/local/lib/python3.11/asyncio/locks.py", line 213, in wait
    |     await fut
    | asyncio.exceptions.CancelledError: Cancelled by cancel scope 7fb2027f7910
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Exception Group Traceback (most recent call last):
    |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 109, in __call__
    |     await response(scope, receive, send)
    |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 270, in __call__
    |     async with anyio.create_task_group() as task_group:
    |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 664, in __aexit__
    |     raise BaseExceptionGroup(
    | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 273, in wrap
      |     await func()
      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 134, in stream_response
      |     return await super().stream_response(send)
      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 262, in stream_response
      |     async for chunk in self.body_iterator:
      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 98, in body_stream
      |     raise app_exc
      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
      |     await self.app(scope, receive_or_disconnect, send_no_error)
      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
      |     raise exc
      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
      |     await self.app(scope, receive, sender)
      |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
      |     raise e
      |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
      |     await self.app(scope, receive, send)
      |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
      |     await route.handle(scope, receive, send)
      |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 443, in handle
      |     await self.app(scope, receive, send)
      |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
      |     await super().__call__(scope, receive, send)
      |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
      |     await self.middleware_stack(scope, receive, send)
      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
      |     raise exc
      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
      |     await self.app(scope, receive, _send)
      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
      |     raise exc
      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
      |     await self.app(scope, receive, sender)
      |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
      |     raise e
      |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
      |     await self.app(scope, receive, send)
      |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
      |     await route.handle(scope, receive, send)
      |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
      |     await self.app(scope, receive, send)
      |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
      |     response = await func(request)
      |                ^^^^^^^^^^^^^^^^^^^
      |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
      |     raw_response = await run_endpoint_function(
      |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
      |     return await dependant.call(**values)
      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "/usr/local/lib/python3.11/site-packages/serge/routers/chat.py", line 44, in create_new_chat
      |     params = ChatParameters(
      |              ^^^^^^^^^^^^^^^
      |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
      | pydantic.error_wrappers.ValidationError: 1 validation error for ChatParameters
      | n_gpu_layers
      |   none is not an allowed value (type=type_error.none.not_allowed)
      +------------------------------------
```

### Confirmations

- [X] I'm running the latest version of the main branch.
- [X] I checked existing issues to see if this has already been described.

**Comment by gitwildnow** [comment]
Sorry now somehow it appears to be working. I can't tell what made it start answering prompts now.

**Comment by gaby** [comment]
@gitwildnow CPU are supported this is a bug introduced in https://github.com/serge-chat/serge/pull/732

I will fix it and release v0.4.0

**Comment by gitwildnow** [comment]
Now it appears to be working. I see the (new to me) GPU Layers parameter too when I look at the layer settings in my browser. I don't *think* I saw that earlier when I was having the problem. I wonder if my Chrome browser was caching an old version of the setup page that didn't include this setting?

**Comment by gaby** [comment]
@gitwildnow Could be, just to be sure. Close your browser and try again or try from a different browser.

**Comment by k0gen** [comment]
@gitwildnow or just open new Private Window and try again
